### ISSUE TITLE
3 fold repbug

### ISSUE THREAD

**Issue by Trey2k** [WeaselChess/Weasel#17]
`position startpos moves g1f3 c7c5 c2c4 g8f6 b1c3 e7e6 g2g3 b7b6 f1g2 c8b7 e1g1 f8e7 f1e1 f6e4 d2d4 e4c3 b2c3 e8g8 e2e4 d7d6 c1f4 d8c7 g2f1 b8c6 f1d3 e6e5 d4e5 d6e5 f4e3 a8d8 d1e2 d8d6 a1d1 f8d8 d1d2 e7f6 e1d1 d8d7 g3g4 f6e7 g4g5 c7d8 e2f1 a7a6 f1e2 b7a8 g1f1 d6e6 f1g1 a8b7 g1h1 d8c7 h1g1 c7c8 h2h4 e6d6 h4h5 f7f6 f3h4 f6g5 h4f5 d6f6 f5e7 c6e7 e3g5 f6d6 f2f4 e7c6 e2h2 h7h6 g5h4 e5f4 h2f4 g7g5 h5g6 d6g6 g1h1 d7f7 f4h2 c8g4 d1g1 g4g1 h2g1 g6g1 h1g1 c6e5 d3e2 b7e4 d2d6 f7g7 g1f1 g7g6 d6g6 e4g6 h4d8 g8f7 d8b6 e5d7 b6c7 h6h5 f1g2 d7f6 c7g3 f7e6 g2f3 g6b1 a2a3 b1f5 f3f4 f5g4 e2d3 f6d7 g3f2 e6d6 f2e3 a6a5 e3f2 d7b6 f2g3 d6e6 f4g5 e6d7 g3f2 d7d6 f2g3 d6c6 d3e4 c6d7 g3f2 d7d6 f2g3 d6e7 g3f2 e7d6`

This position is reported as 3 fold rep when it should not be. Been struggling with 3 fold bugs all day.

**Comment by ChristianHering** [comment]
Fixed in https://github.com/WeaselChess/Weasel/commit/898f0662086843a06bebf9222b14310dc1ddb59f

**Comment by Trey2k** [comment]
Fixed again in bf6e5ab4a7bfc7bedf785c1e9c2aea5cf7a32359
