### ISSUE TITLE
Switching should only happen on first word

### ISSUE THREAD

**Issue by Trey2k** [WeaselChess/Weasel#3]
In UCI switching should only be done on the first word of the command because any number of arguments can follow.

https://github.com/WeaselChess/Weasel/blob/f413417d98a317768096f453cbd2b92c338ef4c3/uci/uci.go#L24

**Comment by ChristianHering** [comment]
Fixed in https://github.com/WeaselChess/Weasel/commit/021f05de8c04aacfc59891c922d79c4c618450f3
